
services:
  # web:
  #   build: ./flutter
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./flutter:/app
    
  server:
    build: ./server
    ports:
      - "8001:80"
    environment:
      FLASK_DEBUG: "true"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CHROMA_PERSISTENT_DIR: ".chromadb/"
    volumes:
      - ./server:/app

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #       - '6379:6379' 