
services:
  web:
    build: ./flutter
    ports:
      - "8000:80"
    volumes:
      - ./flutter:/app
    
  server:
    build: ./server
    ports:
      - "8001:80"
    environment:
      FLASK_DEBUG: "true"
    volumes:
      - ./server:/app
      
  redis:
    image: "redis:alpine"
    ports:
        - '6379:6379' 