
services:
  client:
    build: ./flutter
    ports:
      - "${LOCAL_CLIENT_PORT}:80"
    volumes:
      - ./flutter:/app # Hotload client code changes
    
  server:
    build: ./server
    ports:
      - "${LOCAL_SERVER_PORT}:80"
    environment:
      # Keys
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Server config
      FLASK_DEBUG: "true" # Hot reload server code changes
      # Weaviate
      WEAVIATE_PORT: ${LOCAL_WEAVIATE_PORT}
      # File storage
      FILE_STORAGE_DIR: ${FILE_STORAGE_DIR} # Save downloaded files here
      # MongoDB
      MONGO_HOST: ${LOCAL_MONGO_HOST}
      MONGO_PORT: ${LOCAL_MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./server:/app # Hot reload server code changes
      - file_data:${FILE_STORAGE_DIR}

  mongodb:
    image: mongo:latest
    ports:
      - "${LOCAL_MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:${MONGO_PERSISTENCE_DIR}

  weaviate:
    image: semitechnologies/weaviate:1.19.5
    ports:
    - "${LOCAL_WEAVIATE_PORT}:80"
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: ${WEAVIATE_PERSISTENCE_DIR}
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:${WEAVIATE_PERSISTENCE_DIR}

volumes:
  mongodb_data:
  weaviate_data:
  file_data: